apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crm-server-data
  namespace: crm-sales
  labels:
    app.kubernetes.io/name: crm-server
    app.kubernetes.io/part-of: crm-sales-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
