apiVersion: v1
kind: Service
metadata:
  name: crm-server
  namespace: crm-sales
  labels:
    app.kubernetes.io/name: crm-server
    app.kubernetes.io/part-of: crm-sales-platform
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: crm-server
---
apiVersion: v1
kind: Service
metadata:
  name: crm-web
  namespace: crm-sales
  labels:
    app.kubernetes.io/name: crm-web
    app.kubernetes.io/part-of: crm-sales-platform
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: crm-web
